### ISSUE TITLE
有人能告诉我这怎么用吗？

### ISSUE THREAD

**Issue by oit63** [ssstk/cngrok#1]
说好的 Node.js ，全是go，根本找不到入口啊，这仓库到底是不是源码啊。。。

**Comment by ssstk** [comment]
大哥 ngrok 就是go语言写的啊 这里只是对ngrok 二次开发！！

**Comment by ssstk** [comment]
close

**Comment by oit63** [comment]
大哥能写下怎么跑吗？我没写过go，看这个项目不知道跑哪个可以把服务端跑起来。
